### ISSUE TITLE
User feedback 20240906

### ISSUE THREAD

**Issue by fei666888** [RaspSDR/server#1]
1. static IP address cannot be configured.
2. other users can adjust the attenuator.Add permission control options to the attenuator, similar to kiwisdr.
3. GPS fix counter does not go up.
4. Added 61.44M/122.88M sampling rate switching option, allowing users to choose 30M bandwidth or 60M bandwidth

**Comment by howard0su** [comment]
all are fixed in the latest version. Will resolve this when it is released.
