### ISSUE TITLE
Navtext/DSC not working - no decode

### ISSUE THREAD

**Issue by neil969** [RaspSDR/server#10]
Received my device today :)  Works well out of the box! 
I see no "chat" for the Web-888 so I am writing issues here on the few things I see ( I saw a reddit, but it seems to have been killed by the admins). If you don't want these here please tell me. 

I am running the Alpha channel code  ( currently v2024.1001 )  and the Navtext  decoder does not work.
When it is called, the top of the screen remains black - no "baud" or "error" indicators etc.  Nothing happens when there is a fully decodeable Navtext signal.   
The panel on the bottom left of the screen is also missing some of the fields seen in KiwiSDR's. 
I don't know if  it is disabled in the code or not, if it is , any idea when we will see it working? 

I have seen the same results using other Web-888's from rx.rx-888.com
M0KNC  
EDIT -- I just noticed the the log says:
Tue Oct  1 21:32:51 01:05:28.464 0............                 EXT ext_is_locked_status SET: rx0 ext_client_init=0(is_locked) 

Why is that?

**Comment by neil969** [comment]
Further to this - I have discovered that the DSC & Navtext decoders DO work if you launch the FSK decoder from the extensions panel... And the select Navtext or DSC from there...  
So the issue really is that clicking on  frequency tag for a DSC or NavText frequency, or selecting the Navtext/DSC decoder does not launch the decoder properly.
![image](https://github.com/user-attachments/assets/ac09d74c-f9bd-4c36-b126-86791006a28a)
Clicking on any of these will not launch the correct decoder

**Comment by howard0su** [comment]
it is fixed in the latest version.
