### ISSUE TITLE
DRM Scedule site connection fails

### ISSUE THREAD

**Issue by neil969** [RaspSDR/server#11]
I only received my Web-888 today, and have not managed to receive any DRM yet but when firing up the DRM extension it says in a yellow box at the top  "can't contact server using default data" . Therefore the scheduled frequencies are all wrong.
 
I am using the Alpha Channel - Currently v2024.1001 , and again, I can see the same issue on other receivers in rx.rx-888.com 
![image](https://github.com/user-attachments/assets/9be67145-8fc7-4b95-b2ac-53bff497dbc6)

**Comment by littlebear0729** [comment]
I checked DevTools and found a request to URL: http://downloads.rx-888.com/webconfig/drmrx.cjson, and this request encountered a CORS error.

**Comment by littlebear0729** [comment]
Also, FAX decoding extension is facing the same problem while sending a request to: http://downloads.rx-888.com/webconfig/FAX_freq_menus.cjson.
Maybe some Cross-Origin security setting of the domain "downloads.rx-888.com" should change?

**Comment by howard0su** [comment]
I will fix it. The configuration of server side is override by some unknown problem.

**Comment by howard0su** [comment]
fixed, please check.

**Comment by littlebear0729** [comment]
It's now working.
