### ISSUE TITLE
cannot download FAX images

### ISSUE THREAD

**Issue by neil969** [RaspSDR/server#12]
When recording a FAX , once you stop the recording ( after X number of lines) it says "processing" and then you get a "broken link" icon ( see image below). When you click on the icon it says  "the image at "http://web-888.local:8073/kiwi.data/fax.ch0_1.gif" cannot be displayed because it contains errors"
![image](https://github.com/user-attachments/assets/34351e68-d241-44ff-a0ff-6b9829037df1)
I have tried on other WEB-888's from rx.rx-888.com with the same result
Running the most recent Alpha channel code.

The log doesn't seem to give much of a clue 
Wed Oct  2 07:30:21 00:33:39.152 0.2.......... 0               FAX msg <SET fax_shift=0.452148>
Wed Oct  2 07:30:21 00:33:39.152 0.2.......... 0               FAX shift=0.452148
Wed Oct  2 07:30:39 00:33:57.670 0.2.......... 0               FAX msg <SET fax_file_close>
Wed Oct  2 07:30:39 00:33:57.670 0.2.......... 0               FAX fax_file_close

(again, please let me know if there is a different place to discuss these issues,  otherwise I will keep adding issues here :) )

![image](https://github.com/user-attachments/assets/9a71d0ed-b437-43fe-aead-b8c96ca7cbb0)

**Comment by littlebear0729** [comment]
I'm facing the same problem and here's my temporary solution:
You can try right-click at the top of the webpage where the preview image at, and click 'save as' to download image.

**Comment by howard0su** [comment]
confirm this is a bug.

**Comment by howard0su** [comment]
This is due to the base image is missing a package netpbm. auto update may not help in this case. Please upgrade the image to 2024.1007 or above.
