### ISSUE TITLE
ALE decoder not working - from the "test" (at least) 

### ISSUE THREAD

**Issue by neil969** [RaspSDR/server#13]
When pressing "test" on the ALE_2G decoder  the blue line progresses and you can hear the signal from the file, but nothing is decoded on the screen.
I have left it scanning across the Milcom ALE frequencies for many hours overnight and it decoded nothing, whereas I would have expected to see a few "soundings" at least, so it may not be decoding at all.

using the Alpha channel v2024.1001 - I have tested  the "test"  on a couple of others from rx.rx-888.com with the same results. 
( sorry for creating lots of issues, but I have nowhere else to talk about them. ) - I really like this device BTW, I just think once we find the bugs in this fork of KiwiSDR it will be amazing :)  

M0KNC

![image](https://github.com/user-attachments/assets/4caad542-6022-4ef2-a1a4-691879b82c9b)

**Comment by howard0su** [comment]
thank you for your input and take time to test and report bug to us. The product cannot improve without the input from the community.

Confirm this is bug and I will take a look

**Comment by azwirko** [comment]
Confirmed this is also not working over the air.  I setup my KiwiSDR and Web-888 using a power divider running off the same antenna and setup on the same ALE-2G frequency.  The KiwiSDR decoded and printed ALE-2G messages, but the Web-888 did not. 

I'm running Alpha channel v2024.1001.

73

andyz - K1RA

**Comment by howard0su** [comment]
fixed in 2024.1007

**Comment by neil969** [comment]
when will that build be available? :)  ( not on the Alpha download link as of the 8th Oct )

**Comment by howard0su** [comment]
uploaded.
