### ISSUE TITLE
EIBI Database is too old

### ISSUE THREAD

**Issue by howard0su** [RaspSDR/server#14]
Upgrade it to 24A (or 24B is it releases)

**Comment by littlebear0729** [comment]
data source: http://www.eibispace.de/
script csv->kiwi: https://github.com/OH6BG/eibi2kiwi
forum: https://forum.kiwisdr.com/index.php?p=/discussion/comment/17081#Comment_17081
Maybe the database file can also update from server?

**Comment by neil969** [comment]
I think there may be a general issue with downloading data files from the internet fro the web- 888 - I suspect that it is not getting the "community" DX Labels either, as I have found things I expect to be in there that are missing.  ( assuming it it sharing the community database with the KiwiSDR's)   - We know it can't get the DRM Schedules too. but it CAN do an update of the software from the admin page, so know my Web-888 can download from the internet at least :)

**Comment by howard0su** [comment]
@neil969 do you still have problem to download things like DX labels or DRM schedule? I fixed it already.

**Comment by neil969** [comment]
> @neil969 do you still have problem to download things like DX labels or DRM schedule? I fixed it already.

Ahh..  No sorry, the DRM schedule is OK now :) .. I am not sure about the DX labels, I will keep an eye on it  - 
Thanks Howard

**Comment by howard0su** [comment]
Update to A24 in 2024.1007
