### ISSUE TITLE
Time Synchronization

### ISSUE THREAD

**Issue by poynting** [RaspSDR/server#2]
With v2024.907, there appears to be no time synchronization to UTC, in spite of the GPS page showing no UTC offset. For a new user setting the device up as an FT* skimmer, this means very few signals are decoded even though the device is clearly receiving the signals.

While time synchronization with the onboard GPS PPS should be a long-term goal, in the meantime, it would be helpful to use ntpd to synchronize the device time with the NTP pool for new users plugging the device in for the first time.

I've set up my crontab with the following:

0 * * * * ntpd -p pool.ntp.org

Maybe a configuration setting / environment variable to pick the ntp server would be a simple addition.

**Comment by micked99** [comment]
Also noticed this runnig 907 alpha, time is of about 6,5 minutes behind no mather if gps is enabled or running dissabled and using  network time, tried .

**Comment by howard0su** [comment]
Fixed after 0929.

**Comment by howard0su** [comment]
Since the fix to this issue is createing /etc/network/interfaces file, the auto update will not update OS part currently.

In order to fix this, either flash the full image. or use the workaround of running the following two commands in SSH console:

```bash
# touch /etc/network/interfaces
# lbu commit -d
```

**Comment by poynting** [comment]
I can confirm this change gets chronyd up and running and synchronized. Thanks!
