### ISSUE TITLE
cannot upload a photo to the "webpage" 

### ISSUE THREAD

**Issue by neil969** [RaspSDR/server#29]
On the "webpage" tab in the admin, when I attempt to upload a photo, it always says "Can only upload from local network", when I select a file from my local PC.
I would expect it to simply upload and serve the selected image file...

This is on the Alpha channel  - Installed version: v2024.1008, built Oct 8 2024 13:33:04 
Using FireFox, but I have tried it in Chromium with the same result.
I have also tried multiple formats (jpg, BMP, png etc.) and various size files., always with the same result. 
 
![image](https://github.com/user-attachments/assets/3d7a203e-07cf-4ffe-a545-1dbb69a3412a)

**Comment by littlebear0729** [comment]
Jpeg works fine for me, png is not working.

**Comment by neil969** [comment]
> Jpeg works fine for me, png is not working.

the screenshot was just indicative :) I did try all formats, lots of sizes, etc. etc. etc. - I have had this problem from day 1   - I am on the same network - I have never managed to do this ( and I have reinstalled completely, twice.. 
(jpg screen shot below )  
Are you connecting to the admin using  "web-888.local" or the IP address.. I wonder if that is causing this... I will have a play again..  
![image](https://github.com/user-attachments/assets/ad92dd91-fc4c-4291-b334-9e0fc5b7944c)

**Comment by neil969** [comment]
> > Jpeg works fine for me, png is not working.
> 
> the screenshot was just indicative :) I did try all formats, lots of sizes, etc. etc. etc. - I have had this problem from day 1 - I am on the same network - I have never managed to do this ( and I have reinstalled completely, twice.. (jpg screen shot below ) Are you connecting to the admin using "web-888.local" or the IP address.. I wonder if that is causing this... I will have a play again.. !

OK so here is the problem... when I ping  web-888.local:8073/admin I get ONLY an IP v6 address  if I connect using putty I see the V4 ip address and the V6 address on the eth0 interface..
If I connect to [v4 IP address]:8073/admin  then I CAN upload the picture! - my local PC has a V4 & a V6 address on my network too BTW .
(Note: I can't seem to connect directly by pasting in the V6 ip address - only by allowing it to resolve)
Summary..
I can not upload an image of I connect to web-888.local but I CAN if I connect to the V4 IP address.. 
(P.S. - why is V6 IP sooooo fragile & complicated?  .. LOL )

**Comment by littlebear0729** [comment]
I'm using my IPv4 ip address. Glad to see you work this out, maybe IPv6 support is not good..

**Comment by howard0su** [comment]
This is second report on ipv6. I will check into details.

**Comment by howard0su** [comment]
This behavior is by design.

the current logic only treat the following ip range as local net:
localhost, 127.0.0.1, ::1
10.*, 172.16.*, 192.168.*
fd::*

No check will perform to compare if your ip address is same network. In ipv4 world, likely you will have a local network address. in ipv6 world, likely you will have a global ip address. It is hard (or complex) to tell if you are coming from local net. To make it simple, the above logic is applied.

So this bug is by design.
