### ISSUE TITLE
Waterfall rate very slow when zooming in to 15kHz and 7kHz

### ISSUE THREAD

**Issue by poynting** [RaspSDR/server#3]
v2024.907

I'm using 12 channels for FT* decoding, and using the 13th as a local WebSDR.  When zooming in from about 60kHz to 30kHz, the waterfall speed drops. When zooming in from 30kHz to 15kHz it drops again, and again when zooming to 7.5kHz. These lower bandwidths are very useful for monitoring CW signals, especially during contests or DX pileups, but with the very slow waterfalls speeds, it's hard to get much use out of it.

It would be good if the waterfall rate were consistent with zoom level. 

The kiwiSDR seems to slow down as you zoom in, but then speeds up again. I don't see this behavior with WEB-888.

**Comment by howard0su** [comment]
We may need optimize shared mode of waterfall.

**Comment by littlebear0729** [comment]
I have the same problem, WF11 speed looks normal. But if I keep zoom in to WF12 or even WF13, the waterfall get really slow and stop moving.

**Comment by howard0su** [comment]
This long standing issue is finally fixed. please upgrade.
