### ISSUE TITLE
Feature request: FT8 decoder for 40MHz and 60MHz bands

### ISSUE THREAD

**Issue by OH2LAK** [RaspSDR/server#34]
The current code allows FT8 decoders to autorun on amateur bands from 160m to 6m. Now with the extended frequency range of the WEB888, the experimental 40MHz and 60MHz bands would be needed to be added at least to FT8 decoder selection.

40 MHz (8 m band) FT8 frequency is 40.680 MHz, and on 60 MHz (5 m band) 60.074 MHz

73,
Erik OH2LAK

**Comment by OH2LAK** [comment]
Hi. This change seems not to be yet implemented in the alpha version v2024.1104, built Nov 4 2024 09:22:52?

**Comment by howard0su** [comment]
Fixed in version 1113, please help testing: https://www.rx-888.com/web/downloads.html#_20241113-download
