### ISSUE TITLE
About adding FST4W decoding to Extension.

### ISSUE THREAD

**Issue by ja9mat** [RaspSDR/server#35]
Hello,

I'm a listener of LF and MF WSPR and FST4w mode.
WSPR is OK but I'm now decoding FST4W by redirecting audio output to wsjt-x. So I need PC.

If extension TAB support FST4W, no need PC. So it's a great thing and WEB-888 will be really the next generation SDR!
 
Would you please let me know about the plan to decode FST4W?

73,JA9MAT

**Comment by howard0su** [comment]
We do have the plan regarding add more support of WSJT decoder family. My current thinking regarding decoder of wsjt family is that we can first import FT8 decoder from WSJT-X to replace ft8lib. The challenge is that I don't know much about Fortran. After that, FST4 should be straightforward as it is also using Fortran to decode. Reimplement FST4 in C will be too much work. I will not consider that unless someone create a lib for it.

I cannot commit any timeline so far. I am working on FT8 wsjt fortran code right now.

P.S. If anyone can help me to create a C lib with a simpler API to accept 12K/s audio data from the WSJT-X fortran code, it is so welcome.

**Comment by ja9mat** [comment]
I'm relieved to know why FST4 isn't supported. I hope it will be supported in the future. It's my fault for not checking beforehand when I bought it.

**Comment by howard0su** [comment]
No problem at all. It is a good suggestion.

**Comment by ja9mat** [comment]
My Best Regards,73.

**Comment by howard0su** [comment]
Unfortunately, we recently did some perf measure of ported wsjt-x decoder. It is way too slow for 7010 CPU. We have to stick with the current ft8_lib implementation with some enhancement. I suggest you can use wsjt-x remotely via kiwiclient with Web-888.

**Comment by ja9mat** [comment]
Understood. It's a little disappointing, but I hope you'll consider it again if the opportunity arises.

Well I should have to study about  "kiwiclient". 
But I'm now redirecting the audio into a wsjt-x on my win11 note PC and it's no problem, decoding FST4W mode on LF band well!

Only I think is that it will be more happy to unuse a note PC.

Thanks and have a nice new year!
