### ISSUE TITLE
Change root pasword

### ISSUE THREAD

**Issue by jimjackii** [RaspSDR/server#36]
Hello,

Is there a way to permanently change the root password (e.g. for SSH)?
At the moment it is only temporary and is set to the default password with every restart.

Regards, Steffen

**Comment by jeskko** [comment]
`lbu commit -d` should save most of the changes you've done on the command line (eg. root pw, ssh host key, etc).

**Comment by jimjackii** [comment]
Thanks. Has worked. :-)
