### ISSUE TITLE
Boot loop after auto-upgrade to 2024.1029

### ISSUE THREAD

**Issue by littlebear0729** [RaspSDR/server#38]
Same sd card, re-flash firmware --> Fine
Re-flash firmware, copy my old config folder --> boot loop

**Comment by jimjackii** [comment]
The manual update 20241008 -> 20241029 via the website didn't work for me at all.

Then I just unzipped the zip file and copied it directly to the SD card, but left the config folder untouched.
There were no problems with this.

**Comment by howard0su** [comment]
I am looking into it.

**Comment by howard0su** [comment]
I also added back the links to old firmware. Next time if worse thing happen, you can always download older firmware to go back.

**Comment by littlebear0729** [comment]
> I also added back the links to old firmware. Next time if worse thing happen, you can always download older firmware to go back.

This is exactly what we need, now we are able to download old version of the firmware. Great!
