### ISSUE TITLE
DUC client broken - fails to start due to :  "unrecognized option: k"

### ISSUE THREAD

**Issue by mcurtiscisco** [RaspSDR/server#40]
The DUC client fails to run due to an incorrect option passed to noip2.conf.
Here is the log:

Sat Nov  2 02:50:03 00:03:40.663 .1...........                 DUC: /usr/bin/noip2 -C -c /root/config/noip2.conf -k -u '------' -p '--------------' -U 30 -I eth0 2>&1
Sat Nov  2 02:50:03 00:03:40.915 .1...........                 DUC: status=0
Sat Nov  2 02:50:03 00:03:40.915 .1...........                 DUC: </usr/bin/noip2: unrecognized option: k

USAGE: noip2 [ -C [ -F][ -Y][ -U #min]
	[ -u username][ -p password][ -x progname]]
	[ -c file][ -d][ -D pid][ -i addr][ -S][ -M][ -h]

Version L

**Comment by howard0su** [comment]
Fixed in new version, please help testing: https://www.rx-888.com/web/downloads.html#_20241113-download
