### ISSUE TITLE
Pls ad wspr on 6m and 2m

### ISSUE THREAD

**Issue by micked99** [RaspSDR/server#44]
There is no wspr option on 50Mhz and 144Mhz.

Tnx //Mikael

**Comment by micked99** [comment]
Yes, they are present on the admin page but not from the main page (picture)
![2024-11-12 23_33_13-Greenshot](https://github.com/user-attachments/assets/9dfd995f-b44b-484d-be8a-2c7d5c23cd3a)

**Comment by howard0su** [comment]
Fixed in new version, please help testing: https://www.rx-888.com/web/downloads.html#_20241113-download
