### ISSUE TITLE
FT4 in Extensions 

### ISSUE THREAD

**Issue by ja9mat** [RaspSDR/server#46]
Something bad in FT4 mode in extensions.
I select 10m FT4 but another frequency set.

Hidehiko JA9MAT.

**Comment by howard0su** [comment]
regression. will fix in new release.

**Comment by ja9mat** [comment]
Ok thanks!

**Comment by jeskko** [comment]
https://github.com/RaspSDR/server/pull/48 should fix this.

**Comment by howard0su** [comment]
Fixed in new version, please help testing: https://www.rx-888.com/web/downloads.html#_20241113-download

**Comment by ja9mat** [comment]
Ok thanks. It works.Hidehiko. 2024/11/14 10:13、Howard Su ***@***.***>のメール:﻿
Fixed in new version, please help testing: https://www.rx-888.com/web/downloads.html#_20241113-download

**Comment by ja9mat** [comment]
﻿Ok thanks. It works.Hidehiko. 2024/11/14 10:13、Howard Su ***@***.***>のメール:﻿
Fixed in new version, please help testing: https://www.rx-888.com/web/downloads.html#_20241113-download
