### ISSUE TITLE
Admin interface - Webpage missing "antenna" field.

### ISSUE THREAD

**Issue by mcurtiscisco** [RaspSDR/server#47]
The Web-888 admin page for the "Webpage" settings is missing the "antenna" configuration box.
This causes the web-888 user page to always show a "Mini-Whip" antenna type.
![antenna](https://github.com/user-attachments/assets/11587091-1fb6-4c88-a398-633b962f38af)

**Comment by howard0su** [comment]
You can configure antenna on Public Page. They are using the same configuration entry in the system.
