### ISSUE TITLE
proxy.rx-888 "Secure connection failed"  

### ISSUE THREAD

**Issue by neil969** [RaspSDR/server#51]
I set up my web-888 and authorised it through the default proxy, but the proxy redirect fails with a "secure connection failed" "Error code: SSL_ERROR_RX_RECORD_TOO_LONG"  error in FireFox & Chromium ( at least) 

To reproduce:
Try to go to any web-888 server that is proxied via proxy.rx-888 
eg. mine https://m0knc.proxy.rx-888.com:8073/
or from the list of public servers..
https://sw_web_888_sdr.proxy.rx-888.com:8073/
https://zl2p.proxy.rx-888.com:8073/

![image](https://github.com/user-attachments/assets/f7acd9be-99f3-48bc-9959-1a54d719ede0)

**Comment by howard0su** [comment]
Proxy is http protocol right now.

**Comment by neil969** [comment]
> Proxy is http protocol right now.

Fair enough, but every browser I have tried will not work, - This error  (SSL_ERROR_RX_RECORD_TOO_LONG) seems to show that something on the server end is expecting SSL, so the local browser gives not option of bypassing https.

**Comment by csylvain** [comment]
i can confirm Firefox refuses to "play nicely". in Firefox, i delved into adding both SSL certificate exceptions (in my efforts to add a https2http proxy to frpc), and exceptions to "HTTPS-Only Mode". absolutely nothing seems to affect Firefox's insistence on using SSL.

there is, however, a workaround: use Chrome. and only Chrome.

Chrome does play nicely and successfully interacts with the frp proxy
