### ISSUE TITLE
Version 2024.1130 "Build Failed , and can't find the build.log file

### ISSUE THREAD

**Issue by neil969** [RaspSDR/server#53]
Hi,
   I have my web-888 on the "alpha channel" and I noticed yesterday that there is a new build from 30th Nov, but mine had not updated.
I tried forcing an update but it said:

"Installed version: v2024.1115, built Nov 15 2024 14:42:31
Build failed, check /root/build.log file"

the log in the admin when I tried again this morning says:
"Mon Dec  2 08:00:46 14:35:35.472 0.23.........               L UPDATE: version changed, current 2024.1115, new 2024.1130
Mon Dec  2 08:00:46 14:35:35.472 0.23.........               L UPDATE: installing new version..
Mon Dec  2 08:00:53 14:35:42.527 0.23.........               L UPDATE: fetch binary status=0x00007f00
Mon Dec  2 08:00:54 14:35:42.703 0.23.........               L UPDATE: Build failed, check /root/build.log file"

*So I ssh'd in and their is no /root/build.log file*
I had a look around in other directories too, but I can't find it...

So two questions
1 Where would the build.log file gone 
2 Why is it failing to build, are others having the same issue? 

Also I don't want to bombard  github with small "discussion" things ( like why is the DRM schedule out of date again)  - has anyone set up a forum or mailing list for the web-888? It was on Reddit for a little while but the Moderators there are Vogons & they killed it.

**Comment by Tony-QQ** [comment]
Groupio has a page to discuss web-888 issues.

https://groups.io/g/NextGenSDRs/topics?sidebar=true

**Comment by neil969** [comment]
> Groupio has a page to discuss web-888 issues.
> 
> https://groups.io/g/NextGenSDRs/topics?sidebar=true

Thanks.. It is a bit broad, but i have subscribed to it  ;)

**Comment by neil969** [comment]
Just for the record, I did just download & copy it onto an SD card ( with my config) and all is well, but I still don't know why it points to a place where the build logs are not located ..

**Comment by howard0su** [comment]
this is a regression identified recently. Please update to latest via zip package.
