### ISSUE TITLE
Where is the 13th channel?

### ISSUE THREAD

**Issue by sjunger** [RaspSDR/server#58]
There are only 12 channels (RX0 to RX11) in the software!

I don't know where other users see 13 channels.

![image](https://github.com/user-attachments/assets/597a62ed-f69c-4d1d-8a67-ccc3a8df9145)

**Comment by micked99** [comment]
If you run in 64NMhz bw it now only have 12 bands for better stability, if you reduce to 32Mhz bw you will see 13 bands

**Comment by sjunger** [comment]
Thanks for the information.
Unfortunately, this information cannot be found anywhere. For use with FT8 and WSPR, the restriction is fine for me, as long as you do not use the 6m band or can do without it.

**Comment by sjunger** [comment]
Will there be a software solution to improve stability or is this a limitation of the hardware?

**Comment by micked99** [comment]
Lets see what the developers say.

in the meantime if you haven't already, have a look here, lots of discussion of the 888
https://groups.io/g/NextGenSDRs

**Comment by sjunger** [comment]
All right, I have registered in the group.

**Comment by Tony-QQ** [comment]
> Thanks for the information.
> Unfortunately, this information cannot be found anywhere. For use with FT8 and WSPR, the restriction is fine for me, as long as you do not use the 6m band or can do without it.

You can find the information about this in this page.
https://rx-888.com/web/downloads.html#_20241113-download

**Comment by sjunger** [comment]
Hi Tony,

Thanks for pointing out where to find the information, which is definitely worth knowing for operation.

I would still prefer this to be in the user manual.

But I don't want to dwell on it any further, as my question has been answered and I'm closing the issue.

73 Stefan
