### ISSUE TITLE
Power off button not shutting off device

### ISSUE THREAD

**Issue by winstonsf** [RaspSDR/server#59]
After clicking the Web-888 power off button and then Confirm from the Control page, the device seems to stay powered on though the server appears off. The fan continues spinning, the ethernet light blinks, and the D3 LED is lit. The expected behavior is that the device should shut off entirely.

**Comment by jimjackii** [comment]
The button is a little misleading - there is no real off switch on the Web-888. Only the Linux system is shut down.

Removing the power supply should not be a problem, as the Linux only mounts the SD card read-only.

The fan is also permanently connected to 5V and is not switched off.

Regards, Steffen

**Comment by howard0su** [comment]
Web-888 doesn't have hardware to complete shutdown the board. I will remove this button in next version to avoid confusion.
