### ISSUE TITLE
Failed checksum latest firmware download 20240929

### ISSUE THREAD

**Issue by JonFear** [RaspSDR/server#9]
Getting failed checksum when downloading via the admin portal... 20240915 installed.

**Comment by howard0su** [comment]
Can you try again? I didn't repro.

**Comment by JonFear** [comment]
Hi Howard

No, still fails checksum..

Sorry!

Jon

**Comment by howard0su** [comment]
can you verify latest version if it solves your problem? If the problem persists, I suggest you manually update your firmware via zip package.
